apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pretend-aws-data
  namespace: app-dev
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
